name: folk-frontend-automation
on: workflow_dispatch
jobs:
  get-code:
    runs-on: ubuntu-latest
    steps:
      - name: get frontend code
        uses: actions/checkout@v4
      - name: install ndoe on runner
        uses: actions/setup-node@v3
        with:
          node-version: 16.17
      - name: install dependecies
        run: npm ci

