name: folk-frontend-automation
on: workflow_dispatch

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Git Version
        id: version
        uses: codacy/git-version@2.8.0
      
      - name: Use the version
        run: |
          echo ${{ steps.version.outputs.version }}
      - name: Use the previous version
        run: |
          echo ${{ steps.version.outputs.previous-version }}

      - name: Tag commit
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: ${{ steps.version.outputs.version }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: get frontend code
        uses: actions/checkout@v4
      - name: install ndoe on runner
        uses: actions/setup-node@v3
        with:
          node-version: 16.17
      - name: install dependecies
        run: npm ci